services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/my.cnf
